"""Add vendor_id to NFA model

Revision ID: d7a0bce5af11
Revises: 
Create Date: 2026-02-15 16:04:56.162189

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7a0bce5af11'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nfa', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vendor_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_nfa_vendor_id', 'vendors', ['vendor_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nfa', schema=None) as batch_op:
        batch_op.drop_constraint('fk_nfa_vendor_id', type_='foreignkey')
        batch_op.drop_column('vendor_id')

    # ### end Alembic commands ###
